### ISSUE TITLE
Can't compile with newest Teensyduino

### ISSUE THREAD

**Issue by phantomy1** [Tinwelint78/eBaghet#6]
I'm following the instructions of this Repo to use it on my Teensy 4.0. I downloaded the forked version of Mozzi etc. I'm using the newest version of Teensyduino 1.58.1 and the newest Arduino IDE 2.2.1. I also downloaded and unzipped the eBaghet sketchbook to compile it. I would like to look into the build notes but the original website with the build instructions doesn't exist anymore.

First I get this error message:
f:\Arduino Sketchbooks\libraries\Mozzi-master\MozziGuts.cpp:33:10: fatal error: HardwareTimer.h: No such file or directory
   33 | #include "HardwareTimer.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

When I update the forked Mozzi from 1.0.3 to 1.1.0 I get this error:

In file included from f:\Arduino Sketchbooks\libraries\Mozzi/MozziGuts.h:206,
                 from C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:29:
f:\Arduino Sketchbooks\libraries\Mozzi/AudioConfigTeensy4.h:4:2: warning: #warning If you get a compilation error you should probably update Teensyduino to its latest version [-Wcpp]
    4 | #warning If you get a compilation error you should probably update Teensyduino to its latest version
      |  ^~~~~~~
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:71: warning: "CONTROL_RATE" redefined
   71 | #define CONTROL_RATE 256 //512 // 64 // powers of 2 please
      | 
In file included from C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:29:
f:\Arduino Sketchbooks\libraries\Mozzi/MozziGuts.h:46: note: this is the location of the previous definition
   46 | #define CONTROL_RATE 64
      | 
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino: In function 'void updateControl()':
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:590:14: warning: unused variable 'fb' [-Wunused-variable]
  590 |         byte fb = 0;
      |              ^~
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:591:13: warning: unused variable 'sensor_val' [-Wunused-variable]
  591 |         int sensor_val = 0;
      |             ^~~~~~~~~~
In file included from C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/core_pins.h:33,
                 from C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/wiring.h:39,
                 from C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/WProgram.h:46,
                 from C:\Users\User\AppData\Local\Temp\arduino\sketches\812D4A939E627830F76FD51E1B073672\pch\Arduino.h:6:
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino: In function 'uint8_t readCapacitivePin(int)':
C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/pins_arduino.h:142:71: error: cannot convert 'volatile uint32_t*' {aka 'volatile long unsigned int*'} to 'volatile uint8_t*' {aka 'volatile unsigned char*'} in assignment
  142 | #define portOutputRegister(pin)  ((digital_pin_to_info_PGM[(pin)].reg + 0))
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
      |                                                                       |
      |                                                                       volatile uint32_t* {aka volatile long unsigned int*}
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:1967:16: note: in expansion of macro 'portOutputRegister'
 1967 |         port = portOutputRegister ( digitalPinToPort ( pinToMeasure ) );
      |                ^~~~~~~~~~~~~~~~~~
C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/pins_arduino.h:147:71: error: cannot convert 'volatile uint32_t*' {aka 'volatile long unsigned int*'} to 'volatile uint8_t*' {aka 'volatile unsigned char*'} in assignment
  147 | #define portModeRegister(pin)    ((digital_pin_to_info_PGM[(pin)].reg + 1))
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
      |                                                                       |
      |                                                                       volatile uint32_t* {aka volatile long unsigned int*}
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:1969:15: note: in expansion of macro 'portModeRegister'
 1969 |         ddr = portModeRegister ( digitalPinToPort ( pinToMeasure ) );
      |               ^~~~~~~~~~~~~~~~
C:\Users\User\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.58.1\cores\teensy4/pins_arduino.h:146:71: error: cannot convert 'volatile uint32_t*' {aka 'volatile long unsigned int*'} to 'volatile uint8_t*' {aka 'volatile unsigned char*'} in assignment
  146 | #define portInputRegister(pin)   ((digital_pin_to_info_PGM[(pin)].reg + 2))
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
      |                                                                       |
      |                                                                       volatile uint32_t* {aka volatile long unsigned int*}
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:1972:15: note: in expansion of macro 'portInputRegister'
 1972 |         pin = portInputRegister ( digitalPinToPort ( pinToMeasure ) );
      |               ^~~~~~~~~~~~~~~~~
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino: In function 'int updateAudio()':
C:\Users\User\Downloads\eBaghet-master\eBaghet-master\eBaghet\eBaghet.ino:1941:1: warning: control reaches end of non-void function [-Wreturn-type]
 1941 | }
      | ^

exit status 1

Compilation error: exit status 1

Since I'm on the newest IDE etc. and there is nothing more to be updated, please help me to find out what I am doing wrong.

Best regards

**Comment by Tinwelint78** [comment]
Thanks for reporting this. You were not doing anything wrong.

The problem was not your IDE/Teensyduino version: the repository instructions were outdated.

The old setup referenced a forked Mozzi version that does not correctly support Teensy 4.0. In that configuration, Teensy 4 was effectively falling into the wrong hardware path, which is why it tried to include HardwareTimer.h and failed.

When using a newer Mozzi version, the next error came from the legacy TOUCH_CAP implementation in eBaghet. That code uses AVR-style direct capacitive sensing with volatile uint8_t* GPIO register access, which is not compatible with Teensy 4.x, where the GPIO registers are exposed differently.

I have now updated the project and confirmed that it compiles on Teensy 4.0 with the modern setup.

Current status:

do not use the old forked Mozzi from the original instructions

use the current official Mozzi version instead

on Teensy 4.0, TOUCH_CAP is not supported

use TOUCH_SWITCH or TOUCH_MPR121 instead

the old external build-guide link is dead; a local build guide is now included in the repository

So the issue was caused by outdated project instructions plus an unsupported touch-input mode on Teensy 4, not by a mistake in your environment.

Thanks again for the report — it helped identify and fix the outdated setup.
